# Post-install: configure Bitrix modules transformer + transformercontroller
SITE_NAME=@SITE_NAME@
RABBITMQ_HOST=127.0.0.1
RABBITMQ_PORT=5672
RABBITMQ_USER=@RABBITMQ_USER@
RABBITMQ_PASSWORD=@RABBITMQ_PASSWORD@
RABBITMQ_VHOST=@RABBITMQ_VHOST@
