apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" (include "bitrix.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy | default "Cluster" }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443  
  - name: push
    port: 8893
    protocol: TCP
    targetPort: 8893
  - name: pushs
    port: 8894
    protocol: TCP
    targetPort: 8894
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 180  
  selector:
    app: {{ printf "%s-main" (include "bitrix.fullname" .) }}
    {{- include "bitrix.selectorLabels" . | nindent 4 }}  
  type: LoadBalancer
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}  
