{{- if include "bitrix.gitEnabled" . }}
apiVersion: v1
data:
  id_ed25519: {{ .Values.git.secret  }}
kind: Secret
metadata:
  name: {{ printf "%s-git-ssh" (include "bitrix.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}
{{- end}}