apiVersion: v1
data:
  im_settings.conf: |
    #
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' 'close';
    }
    #
    map $http_upgrade  $replace_upgrade {
        default $http_upgrade;
        '' 'websocket';
    }
    #
kind: ConfigMap
metadata:
  name: {{ printf "%s-im-settings.conf" (include "bitrix.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}