apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-index" (include "bitrix.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}
data:
  index.html: |
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <title>200 OK</title>
    </head>
    <body>
    <div>Ping!</div>
    </body>
    </html>