apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-csi-s3" (include "bitrix.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKeyID: {{ .Values.s3.secret.accessKey }}
  secretAccessKey: {{ .Values.s3.secret.secretKey }}
  endpoint: {{ .Values.s3.secret.endpoint }}
  region: {{ .Values.s3.secret.region }}