apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-upload-pv" (include "bitrix.fullname" .) }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.s3.storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.s3.upload.capacity }}
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ printf "%s-upload-pvc" (include "bitrix.fullname" .) }}
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: {{ .Values.s3.bucket }}/upload
    controllerPublishSecretRef:
      name: {{ printf "%s-csi-s3" (include "bitrix.fullname" .) }}
      namespace: {{ .Release.Namespace }}
    nodePublishSecretRef:
      name: {{ printf "%s-csi-s3" (include "bitrix.fullname" .) }}
      namespace: {{ .Release.Namespace }}
    nodeStageSecretRef:
      name: {{ printf "%s-csi-s3" (include "bitrix.fullname" .) }}
      namespace: {{ .Release.Namespace }}
    volumeAttributes:
      capacity: {{ .Values.s3.upload.capacity }}
      mounter: geesefs
      options: "--no-checksum --memory-limit 4000 --max-flushers 32 --max-parallel-parts 32 --part-sizes 25 --dir-mode=0755 --file-mode=0644 --uid=1000 --gid=1000"
